# Site settings
title: Hardik Varia On Tech
tagline: 'erlang postgresql javascript ...'
description: > # this means to ignore newlines until "baseurl:"
  Yet another blog on erlang, postgresql, javascript and
  anything else that I find interesting.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://imprest.github.io" # the base hostname & protocol for your site
paginate: 5
github_username: imprest

# Build settings
markdown: kramdown

# Permalinks
permalink: pretty

# Custom vars
version: 1.0.0

